name: Check Jenkins advisories reports
run-name: Check Jenkins reports 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: "59 23 * * *"
jobs:
  JenkinsCheckReports:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'
            cache: 'pip'
        - name: Install Python packages
          run: pip install -r app/requirements.txt

        - name: Run check
          run: python3 app/rss_feed_reader.py
          env:
            HOW_DEEP_ITEMS_LOOK_BACK: '12'
            LOOKING_DAYS: '365'
            SENSITIVE_PLUGINS: 'HTMLResource;kubernetes'
