name: Docker
run-name: Dockerfile lint and test 🚀
on: [push]
  paths-ignore:
    - '**/README.md'
jobs:
  Hadolint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Validate Dockerfile with Hadolint tools
          run: |
            export VERSION=$(wget -q -O - https://api.github.com/repos/hadolint/hadolint/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
            wget https://github.com/hadolint/hadolint/releases/download/v${VERSION}/hadolint-Linux-x86_64 -O /tmp/hadolint && chmod +x /tmp/hadolint
            /tmp/hadolint -f json --no-fail Dockerfile

  Build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: sentinel:latest