name: Check some Docker actions
run-name: Check some Docker actions 🚀
on:
  workflow_dispatch:
jobs:
  JenkinsDemoCheck:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Login to Docker 
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Pull Docker image
        run: |
          docker pull python:3.11-slim
          docker image ls
