name: Main GHA
run-name: Main gha 🚀
on:
  workflow_dispatch:

jobs:
  GHAworkflow:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Python v.xx
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
