name: Python unit tests
run-name: Python testing 🚀
on: [push]
jobs:
  PythonUnitTests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install tools
          run: pip install pytest feedparser
          
        - name: pytest
          run: pytest tests/
