name: Python unit tests
run-name: Python testing 🚀
on:
  workflow_dispatch:
  push:
    paths:
      - '**/app/'
      - '**/tests/'
jobs:
  PythonUnitTests:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install tools
          run: pip install pytest feedparser pytest-cov
          
        - name: pytest
          run: pytest tests/

        - name: coverage
          run: |
            mkdir coverage/
            coverage run -m pytest tests/
            coverage report -m
            coverage json -o coverage/coverage-summary.json

        - name: 'Report Coverage'
          if: always() 
          uses:  davelosert/vitest-coverage-report-action@v2
