name: Python code linting
run-name: Python linting 🚀
on: [push]
jobs:
  Hadolint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install tools
          run: pip install pytest
          
        - name: pytest
          run: pytest tests/
