name: Python unit tests
run-name: Python testing 🚀
on:
  push:
    paths-ignore:
      - '**/README.md'
jobs:
  PythonUnitTests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install tools
          run: pip install pytest feedparser pytest-cov
          
        - name: pytest
          run: pytest tests/

        - name: coverage
          run: |
            coverage run -m pytest
            coverage report -m
