name: Python code linting
run-name: Python linting 🚀
on:
  push:
    paths:
      - '**/app/'
      - '**/tests/'
jobs:
  PythonLinting:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install tools
          run: pip install flake8 pylint
          
        - name: pylint
          run: pylint app/rss_feed_reader.py

        - name: flake8
          run: flake8 app/rss_feed_reader.py
